# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  name: 'BusinessTools On-Prem Documentation'

steps:
- checkout: self
  clean: true
  submodules: true
  
- task: DocFxTask@0
  displayName: "Build docfx.json"
  inputs:
    solution: 'docfx.json'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_site/jp'
    ArtifactName: 'jp_docs'
    publishLocation: 'FilePath'
    TargetPath: '\\igbgsofsmb2\builds\Reveal\Docs\$(Build.DefinitionName)\$(Build.BuildNumber)\JP'
    Parallel: true
