# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  name: "BusinessTools On-Prem Documentation"

steps:
- checkout: self
  clean: true
  submodules: true


- task: CmdLine@2
  displayName: Pull latest from the templates submodule
  inputs:
    script: 'git pull origin master'
    workingDirectory: 'templates/reveal'

- task: CmdLine@2 
  displayName: Clone Api Docs repo
  continueOnError:  true
  inputs:
    script: git clone http://tfs.infragistics.local:8080/tfs/Engineering/EnterpriseMobility/_git/RevealSdkApiDocs
- task: CmdLine@2 
  displayName: Pull Api Docs repo
  inputs:
    script: git pull
    workingDirectory: $(Build.SourcesDirectory)/RevealSdkApiDocs

- task: CmdLine@2
  displayName: Update submodule of ApiDocs
  inputs:
    script: |
      git submodule init 
      git submodule update
    workingDirectory: $(Build.SourcesDirectory)/RevealSdkApiDocs

- task: DocFxTask@0
  displayName: "Build Desktop Api docfx.json"
  inputs:
    solution: '$(Build.SourcesDirectory)/RevealSdkApiDocs/Desktop/docfx.json'

- task: CmdLine@2
  displayName: Replicate Revea.Sdk.html as Desktop\_site\latest\index.html
  inputs:
    script: copy RevealSdkApiDocs\Desktop\_site\latest\Reveal.Sdk.html RevealSdkApiDocs\Desktop\_site\latest\index.html

- task: DocFxTask@0
  displayName: "Build DotnetServer Api docfx.json"
  inputs:
    solution: '$(Build.SourcesDirectory)/RevealSdkApiDocs/DotnetServer/docfx.json'

- task: CmdLine@2
  displayName: Replicate Revea.Sdk.html as Desktop\_site\latest\index.html
  inputs:
    script: copy RevealSdkApiDocs\DotnetServer\_site\latest\Reveal.Sdk.html RevealSdkApiDocs\DotnetServer\_site\latest\index.html

- task: DocFxTask@0
  displayName: "Build docfx.json"
  inputs:
    solution: 'docfx.json'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'RevealSdkApiDocs/Desktop/_site/'
    Contents: |
      **
    targetFolder: '_site/api/wpf/'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'RevealSdkApiDocs/dotnetserver/_site/'
    Contents: |
      **
    targetFolder: '_site/api/aspnet/'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'RevealSdkApiDocs/JavaServer/'
    Contents: |
      **
    targetFolder: '_site/api/java/latest/'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'RevealSdkApiDocs/Typedoc'
    Contents: |
      **
    targetFolder: '_site/api/javascript/latest'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_site'
    ArtifactName: 'docs_site'
    publishLocation: 'FilePath'
    TargetPath: '\\igbgsofsmb2\builds\Reveal\Docs\$(Build.DefinitionName)\$(Build.BuildNumber)\EN'
    Parallel: true